spring:
  application:
    name: g-52-shop
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
  jpa:
    properties:
      hibernate:
        auto_quote_keyword: true
  mail:
    username: s.a.saratov@gmail.com
    password: ruczmuwwsjuhfbtf
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            protocols: TLSv1.2
            trust: smtp.gmail.com

do:
  accessKey: ${DO_ACCESS_KEY}
  secretKey: ${DO_SECRET_KEY}
  region: ${DO_REGION:nyc3}
  endpoint: ${DO_ENDPOINT:https://nyc3.digitaloceanspaces.com}

key:
  access: W8jJXCyMXrdwOGtyXjmp9L1K+8sHu23pwUxJU66hIkk=
  refresh: zUlSYvfqO7MfYxW0mv4avHwysJObCoYJ3sMRUO2Q78k=

messages:
  hello: Hello from Digital Ocean!